SDMRPC1 ;MTZ/CKU - APPOINTMENT RPC; 07/23/2012  3:02 PM
 ;;6.0;Scheduling;;07/17/2012;
 Q
GETCLN(RV,CLINIC)
 N STATUS,RESULT S STATUS=$$GETCLN^SDMAPI1(.RESULT,CLINIC)
 D MERGE^SDMRPC(.RV,.RESULT)
 I 'STATUS S RV=-1
 Q
LSTCLNS(RV,SEARCH,START,NUMBER)
 N STATUS,RESULT S STATUS=$$LSTCLNS^SDMAPI1(.RESULT,SEARCH,.START,NUMBER)
 D MERGE^SDMRPC(.RV,.RESULT)
 I 'STATUS S RV=-1
 Q
CLNCK(RV,CLN)
 N STATUS,RESULT S STATUS=$$CLNCK^SDMAPI1(.RESULT,CLN)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
CLNRGHT(RV,CLN)
 N STATUS,RESULT S STATUS=$$CLNRGHT^SDMAPI1(.RESULT,CLN)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
CLNVSC(RV,SC)
 N STATUS,RESULT S STATUS=$$CLNVSC^SDMAPI1(.RESULT,SC)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q