SDMRPC2 ;MTZ/CKU - APPOINTMENT RPC; 07/17/2012  10:01 AM
 ;;6.0;Scheduling;;07/17/2012;
 Q
MAKE(RV,DFN,SC,SD,TYPE,LEN,LVL)
 N STATUS,RESULT S STATUS=$$MAKE^SDMAPI2(.RESULT,DFN,SC,SD,TYPE,LEN,LVL)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
CHKAPP(RV,SC,DFN,SD,LEN)
 N STATUS,RESULT S STATUS=$$CHKAPP^SDMAPI2(.RESULT,SC,DFN,SD,LEN)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
CHECKIN(RV,DFN,SD,SC)
 N STATUS,RESULT S STATUS=$$CHECKIN^SDMAPI2(.RESULT,DFN,SD,SC)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
CANCEL(RV,DFN,SC,SD,TYPE,RSN,RMK)
 N STATUS,RESULT S STATUS=$$CANCEL^SDMAPI2(.RESULT,DFN,SC,SD,TYPE,RSN,RMK)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
LSTAPPT(RV,SEARCH,START,NUMBER)
 N STATUS,RESULT S STATUS=$$LSTAPPT^SDMAPI2(.RESULT,SEARCH,START,NUMBER)
 D MERGE^SDMRPC(.RV,.RESULT)
 I 'STATUS S RV=-1
 Q
GETAPPT(RV,TYPE)
 N STATUS,RESULT S STATUS=$$GETAPPT^SDMAPI2(RESULT,TYPE)
 I 'STATUS S RV=-1
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
GETELIG(RV,ELIG)
 N STATUS,RESULT S STATUS=$$GETELIG^SDMAPI2(RESULT,ELIG)
 I 'STATUS S RV=-1
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
SLOTS(RV,SC)
 N STATUS,RESULT S STATUS=$$SLOTS^SDMAPI2(RESULT,SC)
 I 'STATUS S RV=-1
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
GETAPTS(RV,DFN,SD)
 N STATUS,RESULT S STATUS=$$GETAPTS^SDMAPI2(RESULT,DFN,.SD)
 I 'STATUS S RV=-1
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
HASPEND(RV,PAT,DT)
 N STATUS,RESULT S STATUS=$$HASPEND^SDMAPI2(RESULT,PAT,DT)
 I 'STATUS S RV=-1
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
GETPEND(RV,PAT,DT)
 N STATUS,RESULT S STATUS=$$GETPEND^SDMAPI2(RESULT,PAT,DT)
 I 'STATUS S RV=-1
 D MERGE^SDMRPC(.RV,.RESULT)
 Q