SDMRPC ;APPOINTMENT RPC; 07/17/2012  10:01 AM
 ;;6.0;Scheduling;;12/21/2012;
 Q
MERGE(RV,RESULT) 
 I $D(RESULT)=1 D  Q
 . S RV(1)=RESULT
 N NODE,COUNTER S NODE="RESULT",COUNTER=1
 F  S NODE=$Q(@NODE) Q:NODE=""  D
 . S RV(COUNTER)=NODE_"="_@NODE
 . S COUNTER=$I(COUNTER)
 Q