SDMRPC1 ;MTZ/CKU - APPOINTMENT RPC; 07/17/2012  10:01 AM
 ;;6.0;Scheduling;;07/17/2012;
 Q
GETCLN(RV,CLINIC)
 N STATUS,RESULT S STATUS=$$GETCLN^SDMAPI1(.RESULT,CLINIC)
 I 'STATUS S RV=-1
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
LSTCLNS(RV,SEARCH,START,NUMBER)
 N STATUS,RESULT S STATUS=$$LSTCLNS^SDMAPI1(.RESULT,SEARCH,.START,NUMBER)
 I 'STATUS S RV=-1
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
