SDMRPC4 ;MTZ/CKU - APPOINTMENT RPC; 11/08/2012  3:03 PM
 ;;6.0;Scheduling;;12/31/2012;
 Q
CHECKO(RV,DFN,SD,SC) ; SD APPOINTMENT CHECK-OUT 
 N STATUS,RESULT S STATUS=$$CHECKO^SDMAPI4(.RESULT,+$G(DFN),+$G(SD),+$G(SC))
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
DELCO(RV,DFN,SD) ; SD APPOINTMENT CHECK-OUT DEL
 N STATUS,RESULT S STATUS=$$DELCOSD^SDMAPI4(.RESULT,+$G(DFN),+$G(SD),0)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q